sudo: false
language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-25
  - add-on
  - extra
branches:
  only:
  - master
script: "./gradlew ciBuild"
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
after_success:
    - bash <(curl -s https://codecov.io/bash)
